use std::path::PathBuf;

fn main() {
    generate_migrations_index();
    tauri_build::build();
}

// Scans ./migrations/*.sql at build time and emits OUT_DIR/migrations.gen.rs
// containing a static slice of (version, name, sql) tuples ordered by version.
// The runtime applier in src/db/migrations.rs `include!`s this file.
//
// Filenames must look like `NNNN_short_name.sql` (4+ digit version prefix,
// underscore, identifier). Versions must be strictly increasing starting at 1
// with no gaps — a missing version would let a release ship without applying
// what the dev assumed was already in the chain.
fn generate_migrations_index() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let dir = manifest.join("migrations");
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut entries: Vec<(u32, String, PathBuf)> = Vec::new();

    let read = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("migrations dir {} not readable: {e}", dir.display()));

    for ent in read {
        let ent = ent.expect("migration dir entry");
        let path = ent.path();
        if path.extension().and_then(|s| s.to_str()) != Some("sql") {
            continue;
        }
        println!("cargo:rerun-if-changed={}", path.display());
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_else(|| panic!("invalid migration filename: {}", path.display()));
        let (ver_part, name_part) = stem
            .split_once('_')
            .unwrap_or_else(|| panic!("migration {stem} must be NNNN_name.sql"));
        let version: u32 = ver_part.parse().unwrap_or_else(|_| {
            panic!("migration {stem}: leading segment {ver_part:?} is not a number")
        });
        if version == 0 {
            panic!("migration {stem}: version must be >= 1");
        }
        entries.push((version, name_part.to_string(), path));
    }

    entries.sort_by_key(|(v, _, _)| *v);

    for (i, (v, _, p)) in entries.iter().enumerate() {
        let expected = (i as u32) + 1;
        if *v != expected {
            panic!(
                "migration sequence broken: expected version {expected}, found {v} ({})",
                p.display()
            );
        }
    }

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit\n");
    out.push_str("pub static MIGRATIONS: &[Migration] = &[\n");
    for (v, name, path) in &entries {
        let rel = path.strip_prefix(&manifest).unwrap_or(path);
        out.push_str(&format!(
            "    Migration {{ version: {v}, name: {name:?}, sql: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{}\")) }},\n",
            rel.display()
        ));
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("migrations.gen.rs");
    std::fs::write(&dest, out).expect("write migrations.gen.rs");
}
