use std::path::PathBuf;

fn main() {
    generate_migrations_index();
    embed_macos_info_plist();
    tauri_build::build();
}

// On macOS, embed an Info.plist section into the Mach-O so the binary carries
// its own bundle identity (name + icon) when the OS asks "who is this
// executable?" — e.g. the Full Disk Access / Privacy panes. Without this, the
// elevated helper subprocess (spawned via osascript admin) is listed by raw
// binary name ("diskcutter") with a generic icon, instead of "Disk Cutter".
//
// Skip in debug profile: tauri-codegen's dev path embeds its own
// __info_plist via the embed_plist macro (merging Info.plist next to
// tauri.conf.json with CFBundleName + version). A second sectcreate would
// concatenate two plist documents into the same section; macOS reads only
// the first, shadowing our identity keys and surfacing the process as
// "diskcutter" with the parent (Terminal) icon in Activity Monitor.
fn embed_macos_info_plist() {
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("macos") {
        return;
    }
    if std::env::var("PROFILE").as_deref() == Ok("debug") {
        return;
    }
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let plist = manifest.join("Info.plist");
    println!("cargo:rerun-if-changed={}", plist.display());
    // -sectcreate takes 3 args (segment, section, file). Pass via -Wl with
    // commas — cc splits each comma-separated piece into its own ld arg.
    // Scope to the bin only; the staticlib/cdylib outputs don't need it and
    // some linker drivers reject section flags on dylibs.
    println!(
        "cargo:rustc-link-arg-bin=diskcutter=-Wl,-sectcreate,__TEXT,__info_plist,{}",
        plist.display()
    );
}

// Scans ./migrations/*.sql at build time and emits OUT_DIR/migrations.gen.rs
// containing a static slice of (version, name, sql) tuples ordered by version.
// The runtime applier in src/db/migrations.rs `include!`s this file.
//
// Filenames must look like `NNNN_short_name.sql` (4+ digit version prefix,
// underscore, identifier). Versions must be strictly increasing starting at 1
// with no gaps — a missing version would let a release ship without applying
// what the dev assumed was already in the chain.
fn generate_migrations_index() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let dir = manifest.join("migrations");
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut entries: Vec<(u32, String, PathBuf)> = Vec::new();

    let read = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("migrations dir {} not readable: {e}", dir.display()));

    for ent in read {
        let ent = ent.expect("migration dir entry");
        let path = ent.path();
        if path.extension().and_then(|s| s.to_str()) != Some("sql") {
            continue;
        }
        println!("cargo:rerun-if-changed={}", path.display());
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_else(|| panic!("invalid migration filename: {}", path.display()));
        let (ver_part, name_part) = stem
            .split_once('_')
            .unwrap_or_else(|| panic!("migration {stem} must be NNNN_name.sql"));
        let version: u32 = ver_part.parse().unwrap_or_else(|_| {
            panic!("migration {stem}: leading segment {ver_part:?} is not a number")
        });
        if version == 0 {
            panic!("migration {stem}: version must be >= 1");
        }
        entries.push((version, name_part.to_string(), path));
    }

    entries.sort_by_key(|(v, _, _)| *v);

    for (i, (v, _, p)) in entries.iter().enumerate() {
        let expected = (i as u32) + 1;
        if *v != expected {
            panic!(
                "migration sequence broken: expected version {expected}, found {v} ({})",
                p.display()
            );
        }
    }

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit\n");
    out.push_str("pub static MIGRATIONS: &[Migration] = &[\n");
    for (v, name, path) in &entries {
        let rel = path.strip_prefix(&manifest).unwrap_or(path);
        out.push_str(&format!(
            "    Migration {{ version: {v}, name: {name:?}, sql: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{}\")) }},\n",
            rel.display()
        ));
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("migrations.gen.rs");
    std::fs::write(&dest, out).expect("write migrations.gen.rs");
}
